[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_cerberus_demo = "testX83crd4vAgRrvmwXgVQ2r69uCpg8xzh8A5X124x"

[registry]
url = "https://api.apr.dev"

[provider]
#cluster = "Localnet"
cluster = "devnet"
#cluster = "testnet"
#cluster = "mainnet"
wallet = "/Users/anderustarroz/.config/solana/SCFV.json"

[env]
MY_ENV_VAR = "my_value"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/metaplex-program-library/token-metadata/target/deploy/mpl_token_metadata.so"

[[test.genesis]]
address = "SCERbrcgSPwgkrJ7j4TABr17dhYzdgiwPZUSSfFPt8x"
program = "./deps/sol-cerberus/target/deploy/sol_cerberus.so"
